print("****************************************************")
print("1. Create a tuple of 5 of your favorite colors.")
tup1=("Lavender","Blue","violet","green","Red","Blue","black","green")
print(tup1)
print("****************************************************")
print("2. Print the first and last color from the tuple.")
print(f"first color:{tup1[0]}//last color:{tup1[-1]}")
print("****************************************************")
print("3. Find the length of the tuple.")
print(f"length:{len(tup1)}")
print("****************************************************")
print("4. Count how many times a particular color appears in the tuple.")
ct=tup1.count('green')
print(ct,"times appear in tuple")
print("****************************************************")
print("5. Print all colors one by one using a for loop.")
for i in tup1:
    print(i)
print("****************************************************")
print("6. Combine two tuples of colors and print the result.")
a=("hello","how")
b=("are","you")
print(a+b)
print("****************************************************")
print("7. Find the maximum and minimum value from a tuple of numbers.")
tup5=(1,8,5,6,7,2,7)
print(tup1)
print("Maximum",max(tup1))
print("Minimum",min(tup1))
print("in numbers")
print(tup5)
print("Maximum",max(tup5))
print("Minimum",min(tup5))
print("****************************************************")
print("8. Try to change a value in the tuple and observe what happens.")
print(tup1)
li=list(tup1)
li.insert(1,"black")
print(tuple(li))
print("****************************************************")
