print("BIO-DATA")
print("Name: Lavanya")
print("Age: 20")
print("Gender: Female")
print("Date of Birth: 14/02/2005")
print("Mother Name: Selvi")
print("Father Name: Shanmugam")
print("Address:  Madurai, Tamil Nadu")
print("Email: lavanya123@gmail.com")
print("Degree: B.SC .Info Tech")
print("Years of passout:2025")
