print("Bio-Data")
print("---------")
name="lavanya"
print("name:",name)
age=20
print("age:",age)
height=150.5
print("Height:",height)
weight=52
print("weight:",weight)
city="Madurai"
print("city:",city)
is_student=True
print("is_student:",is_student)
Mark=560
print("Mark:",Mark)
pi=3.14
print("pi:",pi)
Sn="St.Antony's Hr.Secondary School"
print("Sn",Sn)
print(type(name))
print(type(age))
print(type(pi))
print(type(is_student))
my_number=10
print("my_number:",my_number,type(my_number))
my_text="welcome"
print("my_text:",my_text,type(my_text))
