print("School Mark List")
print("----------------")
print("Name: Lavanya")
print("Class 10")
print("  School: st.Antony's Higher Secondary School")
print("  Year: 2020")
print("  Percentage: 69.5%")

print("Class 12:")
print("  School: st.Antony's  Higher Secondary School")
print("  Year: 2022")
print("  Percentage: 80.3%")

print("College")
print("  College: Fatima College")
print("  Degree: B.sc.Info Tech")
print("  University: Kamarajar University")
print("  Years: 2022 - 2025")
print("  CGPA: 7.8")