print("************************************")
print("Length")
print("----------------")
name = input("Enter your name: ")
print("Length of your name is:", len(name))
print("----------------")
print("uppercase change")

t1 = input("Enter a string: ")
print("Uppercase:", t1.upper())
print("----------------")
print("lowercase change")
t2 = input("Enter a string: ")
print("Lowercase:", t2.lower())
print("----------------")
print("count()")
t3 = input("Enter a string: ")
print("Number of times 'a' appears:", t3.count('a'))
print("----------------")
print("Starts with")
t4 = input("Enter a string: ")
print("Starts with 'H:", t4.startswith("H"))
print("----------------")
print("endswith")
t5 = input("Enter a Email: ")
print("Ends with '.com':", t5.endswith(".com"))
print("----------------")
print("replace")
t6 = input("Enter a sentence: ")
print("After replacement:", t6.replace("a", "n"))
print("----------------")
print("strip")
t7 = input("Enter a string with spaces: ")
print("After removing spaces:", t7.strip())
print("----------------")
print("capitalize")
t8 = input("Enter a string: ")
print("After capitalization:", t8.capitalize())
print("----------------")
print("")
t9 = input("Enter a sentence: ")
print("Split into words:", t9.split())
print("************************************")
words = input("Enter words separated by space: ").split()
print("Joined string:", "-".join(words))
print("----------------")
print("is check only alpha")
c1 = input("Enter a string: ")
print("Contains only alphabets:", c1.isalpha())
print("----------------")
print("is check only digit")
c2 = input("Enter a string: ")
print("Contains only digits:", c2.isdigit())
print("----------------")
print("string has both letters and numbers")
c3 = input("Enter a string: ")
print("Contains letters and numbers:", c3.isalnum())
print("----------------")
print("check its lower")
text = input("Enter a string: ")
print("All lowercase:", text.islower())
print("----------------")
print("check its upper")
text = input("Enter a string: ")
print("All uppercase:", text.isupper())
print("----------------")
print("its change upper and lower swap")
text = input("Enter a string: ")
print("After swapcase:", text.swapcase())
print("----------------")
print("word’s first letter to uppercase")
text = input("Enter a sentence: ")
print("Title case:", text.title())
print("----------------")
print("string contains only spaces")
text = input("Enter a string: ")
print("Contains only spaces:", text.isspace())

print("************************************")