print("*****************************")
print("1.Create a tuple")
l=(1,5,"lava","maha",14.8)
print(l)
print(l[1:4])
print("*****************************")
print("2. find a size of tuple")
print("length:",len(l))
print("*****************************")
print("3.find a sort of tuple")
l1=(9,2,3,6,8,7)
l2=("lava","maha","alus")
b1=sorted(l1)
b2=sorted(l2)
print("number sorted:",b1,"\nstring sorted:",b2)
print("*****************************")
print("4.unpacked a tuple in several variable")
c=(4,5,76,"lava","this","good",14)
(a1,a2,a3,a4,a5,a6,a7)=c
print("a6 value is ",a6)
print("*****************************")
tupl=(5,4.6,"lava","a",True,[2,4],{'b':8},(7))
print(tupl)
print("*****************************")
print("Convert Tuple to string")
l6=("lava","maha","alus")
d1=str(l6)
print(d1)
print("*****************************")
l7=(23,56,"lava","maha","alus",89,9,65)
print(l7)
print("4 th element from first ",l7[0:4])
print("4 th element from last ",l7[-1:-5:-1])
print("*****************************")
print("Repeated item of a tuple")
l8 = (3, 4, 4, 5, 7, 8, 8, 8, 4, 4)
l81 = list(l8)
printed = []

for i in l81:
    if l81.count(i) > 1 and i not in printed:
        print(f"{i} = {l81.count(i)}")
        printed.append(i)
print("*****************************")
print("element with in tuple")
t = (10, 20, 30, 40, 50)
x = 30
if x in t:
    print(f"{x} is in the tuple")
else:
    print(f"{x} is not in the tuple")
print("Convert list to tuple")
l9=[4,5,6,2,"mar","lava"]
print(l9)
f9=tuple(l9)
print(f9)
print("Remove  an item from a tuple")
tup2=[5,6,4,"lkm","karthi"]
tup3=list(tup2)
tup3.remove(4)
print(tuple(tup3))
print("slice a tuple")
tup3=list(tup2[1:4])
print(tuple(tup3))
print("find index item in a tuple")
print(tup2.index(4))
print("find of tuple")
print("length:",len(tup2))
print("reversae in tuple in python")
tup4=(1, 2, 3)
temp=list(tup4)
temp.reverse()
rev = tuple(temp)
print(rev)
print("convert a given string list to tuple")
text = "hello"
char_tuple = tuple(text)
print(char_tuple)  