print("Positive and even")
print("--------------------")
a=int(input("enter the number:"))
print("This number is positive and even number:",(a>0 and a%2==0))
print("--------------------")
print("Negative or Zero")
print("--------------------")
n=int(input("enter the number:"))
print("This number is Negative or Zero:",(n<0 or n==0))